version: '3.8'

services:
  # Dịch vụ MongoDB
  mongodb:
    image: mongo:latest
    container_name: manga-db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - mongo-data:/data/db

  # Dịch vụ Redis
  redis:
    image: redis:alpine
    container_name: manga-redis
    restart: always
    ports:
      - "6379:6379"
    # Lệnh chạy kèm mật khẩu (tùy chọn nhưng nên có)
    command: redis-server --requirepass password123
    volumes:
      - redis-data:/data

# Định nghĩa nơi lưu trữ dữ liệu vĩnh viễn trên máy thật
volumes:
  mongo-data:
  redis-data: