export const MANGA_CATEGORIES = [
  { id: 'ngon-tinh', label: 'Ngôn Tình' },
  { id: 'dam-my', label: 'Đam Mỹ' },
  { id: 'huyen-huyen', label: 'Huyền Huyễn' },
  { id: 'xuyen-khong', label: 'Xuyên Không' },
  { id: 'trong-sinh', label: 'Trọng Sinh' },
  { id: 'trinh-tham', label: 'Trịnh Thám' },
  { id: 'co-dai', label: 'Cổ Đại' },
  { id: 'chuyen-sinh', label: 'Chuyển Sinh' },
  { id: 'manhwa', label: 'Manhwa' },
  { id: 'truyen-mau', label: 'Truyện Màu' },
  { id: 'comedy', label: 'Comedy' },
  { id: 'manhua', label: 'Manhua' },
  { id: 'romance', label: 'Romance' },
  { id: 'school-life', label: 'School Life' },
  { id: 'action', label: 'Action' },
  { id: 'ecchi', label: 'Ecchi' },
  { id: 'manga', label: 'Manga' },
  { id: 'mystery', label: 'Mystery' },
  { id: 'seinen', label: 'Seinen' },
  { id: 'smut', label: 'Smut' },
  { id: 'supernatural', label: 'Supernatural' },
  { id: 'tragedy', label: 'Tragedy' },
  { id: 'drama', label: 'Drama' },
  { id: 'adventure', label: 'Adventure' },
  { id: 'fantasy', label: 'Fantasy' },
  { id: 'isekai', label: 'Isekai' },
  { id: 'horror', label: 'Horror' },
  { id: 'shounen', label: 'Shounen' },
  { id: 'gender-bender', label: 'Gender Bender' },
  { id: 'psychological', label: 'Psychological' },
  { id: 'slice-of-life', label: 'Slice Of Life' },
  { id: 'mecha', label: 'Mecha' },
  { id: 'martial-arts', label: 'Martial Arts' },
  { id: 'harem', label: 'Harem' },
  { id: 'shoujo', label: 'Shoujo' },
  { id: 'historical', label: 'Historical' },
  { id: 'webtoon', label: 'Webtoon' },
  { id: 'sci-fi', label: 'Sci-Fi' },
  { id: 'josei', label: 'Josei' },
  { id: 'adult', label: 'Adult' },
  { id: 'mature', label: 'Mature' },
  { id: 'sports', label: 'Sports' },
  { id: 'anime', label: 'Anime' },
  { id: 'comic', label: 'Comic' },
  { id: 'cooking', label: 'Cooking' },
  { id: 'one-shot', label: 'One Shot' },
  { id: 'doujinshi', label: 'Doujinshi' },
  { id: 'magic', label: 'Magic' },
  { id: 'live-action', label: 'Live Action' },
  { id: 'soft-yuri', label: 'Soft Yuri' },
  { id: 'yuri', label: 'Yuri' },
  { id: 'shoujo-ai', label: 'Shoujo Ai' },
  { id: 'demons', label: 'Demons' },
  { id: 'shounen-ai', label: 'Shounen Ai' },
  { id: 'thieu-nhi', label: 'Thiếu Nhi' },
  { id: 'soft-yaoi', label: 'Soft Yaoi' },
  { id: 'yaoi', label: 'Yaoi' },
  { id: 'detective', label: 'Detective' },
  { id: 'khac', label: 'Khác' },
];